apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrambot
  labels:
    app: telegrambot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegrambot
  template:
    metadata:
      labels:
        app: telegrambot
    spec:
      containers:
      - name: telegrambot
        image: registry.gitlab.com/fiuba-memo2/ejemplos/telegram-bot-example:0.0.8
        envFrom:
          - secretRef:
              name: botsecret
          - configMapRef:
              name: botconfig
